ValueSet: TumorMarkerTests
Id: onconova-vs-tumor-marker-tests
Title: "Tumor Marker Tests"
Description: "ValueSet containing LOINC and NCI Thesaurus codes for tumor marker laboratory tests and measurements"

* $LOINC#2039-6 "Carcinoembryonic Ag [Mass/volume] in Serum or Plasma"
* $LOINC#19166-8 "Carcinoembryonic Ag [Units/volume] in Serum or Plasma"
* $LOINC#19167-6 "Carcinoembryonic Ag [Moles/volume] in Serum or Plasma"
* $LOINC#40618-1 "Cancer Ag 125 [Units/volume] in Serum or Plasma"
* $LOINC#10334-1 "Cancer Ag 15-3 [Units/volume] in Serum or Plasma"
* $LOINC#24108-3 "Cancer Ag 19-9 [Units/volume] in Serum or Plasma"
* $LOINC#2011-5 "Cancer Ag 242 [Presence] in Serum or Plasma"
* $LOINC#17842-6 "Cancer Ag 27-29 [Units/volume] in Serum or Plasma"
* $LOINC#34256-8 "Cancer Ag 50 [Units/volume] in Serum or Plasma"
* $LOINC#19189-0 "Cancer Ag 549 [Units/volume] in Serum or Plasma"
* $LOINC#17843-4 "Cancer Ag 72-4 [Units/volume] in Serum or Plasma"
* $LOINC#13127-6 "Cancer Ag DM/70K [Units/volume] in Serum or Plasma"
* $LOINC#24474-9 "Cancer associated serum Ag [Units/volume] in Serum"
* $NCIT#C96593 "Circulating Tumor Cell Count"
* $LOINC#98117-5 "Fibroblast growth factor 2 [Mass/volume] in Serum or Plasma"
* $LOINC#87832-2 "Fibroblast growth factor 21.intact [Mass/volume] in Serum or Plasma"
* $LOINC#46699-5 "Fibroblast growth factor 23 [Units/volume] in Plasma"
* $LOINC#54390-0 "Fibroblast growth factor 23.intact [Mass/volume] in Serum or Plasma"
* $LOINC#104259-7 "Fibroblast growth factor 23 [Presence] in Tissue by FISH"
* $LOINC#96461-9 "Gastrin releasing polypeptide prohormone [Mass/volume] in Serum or Plasma by Immunoassay"
* $LOINC#54165-6 "Tumor necrosis factor binding protein [Units/volume] in Serum"
* $LOINC#48663-9 "YKL-40 [Mass/volume] in Serum"
* $LOINC#15060-7 "Enolase.neuron specific [Mass/volume] in Serum or Plasma"
* $LOINC#19193-2 "Enolase.neuron specific [Units/volume] in Serum or Plasma"
* $LOINC#2532-0 "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma"
* $LOINC#9811-1 "Chromogranin A [Mass/volume] in Serum or Plasma"
* $LOINC#25587-7 "Chromogranin A [Moles/volume] in Serum or Plasma"
* $LOINC#47275-3 "S100 calcium binding protein B [Mass/volume] in Serum"
* $LOINC#19195-7 "Prostate specific Ag [Units/volume] in Serum or Plasma"
* $LOINC#2857-1 "Prostate specific Ag [Mass/volume] in Serum or Plasma"
* $LOINC#19197-3 "Prostate specific Ag [Moles/volume] in Serum or Plasma"
* $LOINC#1834-1 "Alpha-1-Fetoprotein [Mass/volume] in Serum or Plasma"
* $LOINC#19176-7 "Alpha-1-Fetoprotein [Units/volume] in Serum or Plasma"
* $LOINC#19177-5 "Alpha-1-Fetoprotein [Moles/volume] in Serum or Plasma"
* $LOINC#55869-2 "Choriogonadotropin.beta subunit [Mass/volume] in Serum or Plasma"
* $LOINC#21198-7 "Choriogonadotropin.beta subunit [Units/volume] in Serum or Plasma"
* $LOINC#2111-3 "Choriogonadotropin.beta subunit [Moles/volume] in Serum or Plasma"
* $LOINC#55868-4 "Choriogonadotropin.beta subunit [Multiple of the median] in Serum or Plasma"
* $LOINC#25390-6 "Cytokeratin 19 [Mass/volume] in Serum or Plasma"
* $LOINC#19182-5 "Cytokeratin 19 [Units/volume] in Serum or Plasma"
* $LOINC#96044-3 "Human epididymis protein 4 [Mass/volume] in Serum or Plasma"
* $LOINC#55180-4 "Human epididymis protein 4 [Moles/volume] in Serum or Plasma"
* $LOINC#17248-6 "Melanin [Units/volume] in Serum or Plasma"
* $LOINC#2607-0 "Melanin [Mass/volume] in Urine"
* $LOINC#13238-1 "Epstein Barr virus Ab [Units/volume] in Serum"
* $LOINC#49178-7 "Epstein Barr virus Ab [Presence] in Serum"
* $NCIT#C199175 "PD-L1 Immune Cell Score"
* $NCIT#C184941 "PD-L1 Tumor Proportion Score"
* $NCIT#C176582 "PD-L1 Combined Positive Score"
* $LOINC#72383-3 "HER2 [Presence] in Tissue by Immunoassay"
* $NCIT#C185751 "HER2/Neu Status by Immunohistochemistry"
* $LOINC#14228-1 "Cells.estrogen receptor/cells in Tissue by Immune stain"
* $LOINC#14230-7 "Cells.progesterone receptor/cells in Tissue by Immune stain"
* $NCIT#C157165 "AR Status by Immunohistochemistry"
* $LOINC#29593-1 "Cells.Ki-67 nuclear Ag/cells in Tissue by Immune stain"
* $LOINC#96272-0 "DNA mismatch repair protein Mlh3 [Presence] in Cancer specimen by Immune stain"
* $LOINC#81691-8 "DNA mismatch repair protein Mlh1 [Presence] in Cancer specimen by Immune stain"
* $LOINC#81692-6 "DNA mismatch repair protein Msh2 [Presence] in Cancer specimen by Immune stain"
* $LOINC#81693-4 "DNA mismatch repair protein Msh6 [Presence] in Cancer specimen by Immune stain"
* $LOINC#81694-2 "Mismatch repair endonuclease PMS2 [Presence] in Cancer specimen by Immune stain"
* $LOINC#21614-3 "CDKN2A gene deletion [Presence] in Blood or Tissue by Molecular genetics method"
* $LOINC#105077-2 "Human papilloma virus DNA [Presence] in Specimen"
* $LOINC#5003-9 "Epstein Barr virus DNA [Presence] in Tissue by Probe"
* $LOINC#108217-1 "Epstein Barr virus DNA [Units/volume] (viral load) in Specimen by NAA with probe detection"
* $NCIT#C165984 "Somatostatin Receptor Type 2 Measurement"
